<a href="https://colab.research.google.com/github/EricaBordon/biblioteca_django/blob/main/Clase_IA_23_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#subir daraset desde un archivo

In [2]:
import pandas as pd
#read a locakl csv file named 'data.scv'
df= pd.read_csv('clase.csv')
df_aux = df
#display the first few row of the dataFrame
print(df.head())

  Nombre y Apellido  Nro_documento  Edad       Ciudad     Servicio Municipal  \
0       Mar�a L�pez        4589213    34     Asunci�n  Recolecci�n de basura
1      Carlos G�mez        5123789    42        Luque      Alumbrado p�blico
2      Ana Mart�nez        3892145    27  San Lorenzo                 Bacheo
3      Jos� Ben�tez        4765123    51      Capiat�           Agua potable
4   Laura Fern�ndez        4987123    30      Lambar�  Recolecci�n de basura

                              Reclamo Estado de Reclamo
0       No pasa el cami�n hace 3 d�as         Pendiente
1  Foco quemado en la calle Principal          Resuelto
2              Bache frente a mi casa        En proceso
3                Baja presi�n de agua         Pendiente
4         Basura acumulada en esquina          Resuelto

1. Convertir todas las columnas en minusculas

In [3]:
df.columns = df.columns.str.lower()
display(df.head())

,nombre y apellido,nro_documento,edad,ciudad,servicio municipal,reclamo,estado de reclamo
0,Mar�a L�pez,4589213,34,Asunci�n,Recolecci�n de basura,No pasa el cami�n hace 3 d�as,Pendiente
1,Carlos G�mez,5123789,42,Luque,Alumbrado p�blico,Foco quemado en la calle Principal,Resuelto
2,Ana Mart�nez,3892145,27,San Lorenzo,Bacheo,Bache frente a mi casa,En proceso
3,Jos� Ben�tez,4765123,51,Capiat�,Agua potable,Baja presi�n de agua,Pendiente
4,Laura Fern�ndez,4987123,30,Lambar�,Recolecci�n de basura,Basura acumulada en esquina,Resuelto

2. Eliminar todos los acentos de las palabras

In [5]:
import unicodedata
import re

def remove_accents_and_special_chars(text):
    if isinstance(text, str):
        # Normalize to NFD (Canonical Decomposition Form) and remove combining characters
        text = unicodedata.normalize('NFD', text)
        text = ''.join(c for c in text if unicodedata.category(c) != 'Mn')
        # Remove non-alphanumeric characters except spaces and hyphens
        text = re.sub(r'[^a-zA-Z0-9\s-]', '', text)
        return text
    return text

# Apply the function to all string columns in the DataFrame
for col in df.columns:
    if df[col].dtype == 'object': # Check if the column contains strings
        df[col] = df[col].apply(remove_accents_and_special_chars)

display(df.head())

,nombre y apellido,nro_documento,edad,ciudad,servicio municipal,reclamo,estado de reclamo
0,Mara Lpez,4589213,34,Asuncin,Recoleccin de basura,No pasa el camin hace 3 das,Pendiente
1,Carlos Gmez,5123789,42,Luque,Alumbrado pblico,Foco quemado en la calle Principal,Resuelto
2,Ana Martnez,3892145,27,San Lorenzo,Bacheo,Bache frente a mi casa,En proceso
3,Jos Bentez,4765123,51,Capiat,Agua potable,Baja presin de agua,Pendiente
4,Laura Fernndez,4987123,30,Lambar,Recoleccin de basura,Basura acumulada en esquina,Resuelto

3. Ekiminar los caracteres especiales

In [6]:
import re

def remove_all_special_chars(text):
    if isinstance(text, str):
        # Keep only alphanumeric characters
        text = re.sub(r'[^a-zA-Z0-9]', '', text)
        return text
    return text

# Apply the function to all string columns in the DataFrame
for col in df.columns:
    if df[col].dtype == 'object': # Check if the column contains strings
        df[col] = df[col].apply(remove_all_special_chars)

display(df.head())

,nombre y apellido,nro_documento,edad,ciudad,servicio municipal,reclamo,estado de reclamo
0,MaraLpez,4589213,34,Asuncin,Recoleccindebasura,Nopasaelcaminhace3das,Pendiente
1,CarlosGmez,5123789,42,Luque,Alumbradopblico,FocoquemadoenlacallePrincipal,Resuelto
2,AnaMartnez,3892145,27,SanLorenzo,Bacheo,Bachefrenteamicasa,Enproceso
3,JosBentez,4765123,51,Capiat,Aguapotable,Bajapresindeagua,Pendiente
4,LauraFernndez,4987123,30,Lambar,Recoleccindebasura,Basuraacumuladaenesquina,Resuelto

4. Contar cuantos valores nulos tiene

In [7]:
print(df.isnull().sum())

nombre y apellido     0
nro_documento         0
edad                  0
ciudad                0
servicio municipal    0
reclamo               0
estado de reclamo     0
dtype: int64

5. Contar cuantos valores vacios tiene

In [9]:
empty_counts = {}
for col in df.columns:
    if df[col].dtype == 'object':
        empty_counts[col] = (df[col] == '').sum()

print("Contador de valores vacios (empty strings) por columna:")
for col, count in empty_counts.items():
    print(f"{col}: {count}")

Count of empty values (empty strings) per column:
nombre y apellido: 0
ciudad: 0
servicio municipal: 0
reclamo: 0
estado de reclamo: 0